# Generated by Django 4.1.2 on 2022-10-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=120)),
                ('machine_name', models.CharField(max_length=120)),
                ('machine_model', models.CharField(max_length=120)),
                ('machine_location', models.CharField(max_length=120)),
                ('machine_doi', models.CharField(max_length=120)),
                ('factory_id', models.CharField(max_length=120)),
            ],
        ),
    ]
